#!/bin/bash

title="`mpc --format \"[%title%]\" | head -n 1`"

STATUS="`mpc status | awk '{ print $1 }' | awk -F/ '{ print $1 }' | tail -2 | head -n 1 | tr -d '[' | tr -d ']' | sed -e "s/\b\(.\)/\u\1/g"`"

echo $title "|" $STATUS